port: 3000
env: development
db_uri: mongodb://localhost:27017
sqs:
  region: us-east-1
  orders_queue:
    url: <your-sqs-url>
    consumers: 1
mailtrap:
  host: smtp.mailtrap.io
  port: 2525
  auth:
    user: <your-user-id>
    pass: <your-password>