port: 3000
env: development
db_uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
sqs:
  region: us-east-1
  orders_queue:
    url: https://sqs.us-east-1.amazonaws.com/520763495267/nodeshop.fifo
